/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The object sent in the PUT /authorizations/{ID} callback.
 */
export interface AuthorizationsIDPutResponse { 
    /**
     * OTP or QR Code if entered, otherwise empty.
     */
    authenticationInfo?: string;
    /**
     * Enum containing response information; if the customer entered the authentication value, rejected the transaction, or requested a resend of the authentication value.
     */
    responseType: string;
}