/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
*/import { ExtensionList } from './extensionList'
import { IndividualTransferResult } from './individualTransferResult'

/**
 * The object sent in the PUT /bulkTransfers/{ID} callback.
 */
export interface BulkTransfersIDPutResponse {
    /**
     * Time and date when the bulk transaction was completed.
     */
  completedTimestamp?: string
    /**
     * List of IndividualTransferResult elements.
     */
  individualTransferResults?: Array<IndividualTransferResult>
    /**
     * The state of the bulk transfer.
     */
  bulkTransferState: string
  extensionList?: ExtensionList
}
