/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ExtensionList } from './extensionList';
import { IndividualQuoteResult } from './individualQuoteResult';


/**
 * The object sent in the PUT /bulkQuotes/{ID} callback.
 */
export interface BulkQuotesIDPutResponse { 
    /**
     * Fees for each individual transaction, if any of them are charged per transaction.
     */
    individualQuoteResults?: Array<IndividualQuoteResult>;
    /**
     * Date and time until when the quotation is valid and can be honored when used in the subsequent transaction request.
     */
    expiration: string;
    extensionList?: ExtensionList;
}