/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExtensionList } from './extensionList'
import { IndividualTransfer } from './individualTransfer'

/**
 * The object sent in the POST /bulkTransfers request.
 */
export interface BulkTransfersPostRequest {
    /**
     * Common ID between the FSPs and the optional Switch for the bulk transfer object, decided by the Payer FSP. The ID should be reused for resends of the same bulk transfer. A new ID should be generated for each new bulk transfer.
     */
  bulkTransferId: string
    /**
     * ID of the related bulk quote.
     */
  bulkQuoteId: string
    /**
     * Payer FSP identifier.
     */
  payerFsp: string
    /**
     * Payee FSP identifier.
     */
  payeeFsp: string
    /**
     * List of IndividualTransfer elements.
     */
  individualTransfers: Array<IndividualTransfer>
    /**
     * Expiration time of the transfers.
     */
  expiration: string
  extensionList?: ExtensionList
}
