/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ExtensionList } from './extensionList';
import { Money } from './money';
import { Party } from './party';
import { TransactionType } from './transactionType';


/**
 * Data model for the complex type IndividualQuote.
 */
export interface IndividualQuote { 
    /**
     * Identifies the quote message.
     */
    quoteId: string;
    /**
     * Identifies the transaction message.
     */
    transactionId: string;
    payee: Party;
    /**
     * SEND for sendAmount, RECEIVE for receiveAmount.
     */
    amountType: string;
    amount: Money;
    fees?: Money;
    transactionType: TransactionType;
    /**
     * Memo that will be attached to the transaction.
     */
    note?: string;
    extensionList?: ExtensionList;
}