/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ErrorInformation } from './errorInformation';
import { ExtensionList } from './extensionList';


/**
 * Data model for the complex type IndividualTransferResult.
 */
export interface IndividualTransferResult { 
    /**
     * Identifies messages related to the same /transfers sequence.
     */
    transferId: string;
    /**
     * Fulfilment of the condition specified with the transaction. **Note:** Either fulfilment or errorInformation should be set, not both.
     */
    fulfilment?: string;
    errorInformation?: ErrorInformation;
    extensionList?: ExtensionList;
}