/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErrorInformation } from './errorInformation'
import { ExtensionList } from './extensionList'
import { Money } from './money'
import { Party } from './party'

/**
 * Data model for the complex type IndividualQuoteResult.
 */
export interface IndividualQuoteResult {
    /**
     * Identifies the quote message.
     */
  quoteId: string
  payee?: Party
  transferAmount?: Money
  payeeReceiveAmount?: Money
  payeeFspFee?: Money
  payeeFspCommission?: Money
    /**
     * The ILP Packet that must be attached to the transfer by the Payer.
     */
  ilpPacket?: string
    /**
     * The condition that must be attached to the transfer by the Payer.
     */
  condition?: string
  errorInformation?: ErrorInformation
  extensionList?: ExtensionList
}
