/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Data model for the complex type PartyIdInfo.
 */
export interface PartyIdInfo { 
    /**
     * Type of the identifier.
     */
    partyIdType: string;
    /**
     * An identifier for the Party.
     */
    partyIdentifier: string;
    /**
     * A sub-identifier or sub-type for the Party.
     */
    partySubIdOrType?: string;
    /**
     * FSP ID (if known).
     */
    fspId?: string;
}