/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
*/import { PartyComplexName } from './partyComplexName'

/**
 * Data model for the complex type PartyPersonalInfo.
 */
export interface PartyPersonalInfo {
  complexName?: PartyComplexName
    /**
     * Date of birth for the Party.
     */
  dateOfBirth?: string
}
