/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
*/import { PartyResult } from './partyResult'

/**
 * The object sent in the PUT /participants/{ID} callback.
 */
export interface ParticipantsIDPutResponse {
    /**
     * List of PartyResult elements that were either created or failed to be created.
     */
  partyList: Array<PartyResult>
    /**
     * Indicate that the provided Currency was set to be supported by each successfully added PartyIdInfo.
     */
  currency?: string
}
