/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
*/import { PartyIdInfo } from './partyIdInfo'

/**
 * The object sent in the POST /participants request.
 */
export interface ParticipantsPostRequest {
    /**
     * The ID of the request, decided by the client. Used for identification of the callback from the server.
     */
  requestId: string
    /**
     * List of PartyIdInfo elements that the client would like to update or create FSP information about.
     */
  partyList: Array<PartyIdInfo>
    /**
     * Indicate that the provided Currency is supported by each PartyIdInfo in the list.
     */
  currency?: string
}
