/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Below are the allowed values for the enumeration. - PASSPORT - A passport number is used as reference to a Party. - NATIONAL_REGISTRATION - A national registration number is used as reference to a Party. - DRIVING_LICENSE - A driving license is used as reference to a Party. - ALIEN_REGISTRATION - An alien registration number is used as reference to a Party. - NATIONAL_ID_CARD - A national ID card number is used as reference to a Party. - EMPLOYER_ID - A tax identification number is used as reference to a Party. - TAX_ID_NUMBER - A tax identification number is used as reference to a Party. - SENIOR_CITIZENS_CARD - A senior citizens card number is used as reference to a Party. - MARRIAGE_CERTIFICATE - A marriage certificate number is used as reference to a Party. - HEALTH_CARD - A health card number is used as reference to a Party. - VOTERS_ID - A voter’s identification number is used as reference to a Party. - UNITED_NATIONS - An UN (United Nations) number is used as reference to a Party. - OTHER_ID - Any other type of identification type number is used as reference to a Party.
 */
export type PersonalIdentifierType = 'PASSPORT' | 'NATIONAL_REGISTRATION' | 'DRIVING_LICENSE' | 'ALIEN_REGISTRATION' | 'NATIONAL_ID_CARD' | 'EMPLOYER_ID' | 'TAX_ID_NUMBER' | 'SENIOR_CITIZENS_CARD' | 'MARRIAGE_CERTIFICATE' | 'HEALTH_CARD' | 'VOTERS_ID' | 'UNITED_NATIONS' | 'OTHER_ID';

export const PersonalIdentifierType = {
    PASSPORT: 'PASSPORT' as PersonalIdentifierType,
    NATIONALREGISTRATION: 'NATIONAL_REGISTRATION' as PersonalIdentifierType,
    DRIVINGLICENSE: 'DRIVING_LICENSE' as PersonalIdentifierType,
    ALIENREGISTRATION: 'ALIEN_REGISTRATION' as PersonalIdentifierType,
    NATIONALIDCARD: 'NATIONAL_ID_CARD' as PersonalIdentifierType,
    EMPLOYERID: 'EMPLOYER_ID' as PersonalIdentifierType,
    TAXIDNUMBER: 'TAX_ID_NUMBER' as PersonalIdentifierType,
    SENIORCITIZENSCARD: 'SENIOR_CITIZENS_CARD' as PersonalIdentifierType,
    MARRIAGECERTIFICATE: 'MARRIAGE_CERTIFICATE' as PersonalIdentifierType,
    HEALTHCARD: 'HEALTH_CARD' as PersonalIdentifierType,
    VOTERSID: 'VOTERS_ID' as PersonalIdentifierType,
    UNITEDNATIONS: 'UNITED_NATIONS' as PersonalIdentifierType,
    OTHERID: 'OTHER_ID' as PersonalIdentifierType
};