/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
*/import { ExtensionList } from './extensionList'
import { GeoCode } from './geoCode'
import { Money } from './money'

/**
 * The object sent in the PUT /quotes/{ID} callback.
 */
export interface QuotesIDPutResponse {
  transferAmount: Money
  payeeReceiveAmount?: Money
  payeeFspFee?: Money
  payeeFspCommission?: Money
    /**
     * Date and time until when the quotation is valid and can be honored when used in the subsequent transaction.
     */
  expiration: string
  geoCode?: GeoCode
    /**
     * The ILP Packet that must be attached to the transfer by the Payer.
     */
  ilpPacket: string
    /**
     * The condition that must be attached to the transfer by the Payer.
     */
  condition: string
  extensionList?: ExtensionList
}
