/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Below are the allowed values for the enumeration. - RECEIVED - Payer FSP has received the transaction from the Payee FSP. - PENDING - Payer FSP has sent the transaction request to the Payer. - ACCEPTED - Payer has approved the transaction. - REJECTED - Payer has rejected the transaction.
 */
export type TransactionRequestState = 'RECEIVED' | 'PENDING' | 'ACCEPTED' | 'REJECTED'

export const TransactionRequestState = {
  RECEIVED: 'RECEIVED' as TransactionRequestState,
  PENDING: 'PENDING' as TransactionRequestState,
  ACCEPTED: 'ACCEPTED' as TransactionRequestState,
  REJECTED: 'REJECTED' as TransactionRequestState
}
