/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
*/import { ExtensionList } from './extensionList'
import { GeoCode } from './geoCode'
import { Money } from './money'
import { Party } from './party'
import { PartyIdInfo } from './partyIdInfo'
import { TransactionType } from './transactionType'

/**
 * The object sent in the POST /transactionRequests request.
 */
export interface TransactionRequestsPostRequest {
    /**
     * Common ID between the FSPs for the transaction request object, decided by the Payee FSP. The ID should be reused for resends of the same transaction request. A new ID should be generated for each new transaction request.
     */
  transactionRequestId: string
  payee: Party
  payer: PartyIdInfo
  amount: Money
  transactionType: TransactionType
    /**
     * Reason for the transaction request, intended to the Payer.
     */
  note?: string
  geoCode?: GeoCode
    /**
     * OTP or QR Code, otherwise empty.
     */
  authenticationType?: string
    /**
     * Can be set to get a quick failure in case the peer FSP takes too long to respond. Also, it may be beneficial for Consumer, Agent, Merchant to know that their request has a time limit.
     */
  expiration?: string
  extensionList?: ExtensionList
}
