/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Refund } from './refund'

/**
 * Data model for the complex type TransactionType.
 */
export interface TransactionType {
    /**
     * Deposit, withdrawal, refund, …
     */
  scenario: string
    /**
     * Possible sub-scenario, defined locally within the scheme.
     */
  subScenario?: string
    /**
     * Who is initiating the transaction - Payer or Payee.
     */
  initiator: string
    /**
     * Consumer, agent, business, …
     */
  initiatorType: string
  refundInfo?: Refund
    /**
     * Balance of Payments code.
     */
  balanceOfPayments?: string
}
