/**
 * Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
 * Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Below are the allowed values for the enumeration. - CONSUMER - Consumer is the initiator of the transaction. - AGENT - Agent is the initiator of the transaction. - BUSINESS - Business is the initiator of the transaction. - DEVICE - Device is the initiator of the transaction.
 */
export type TransactionInitiatorType = 'CONSUMER' | 'AGENT' | 'BUSINESS' | 'DEVICE'

export const TransactionInitiatorType = {
  CONSUMER: 'CONSUMER' as TransactionInitiatorType,
  AGENT: 'AGENT' as TransactionInitiatorType,
  BUSINESS: 'BUSINESS' as TransactionInitiatorType,
  DEVICE: 'DEVICE' as TransactionInitiatorType
}
